services:
  web:
    build: .
    # image: qawamis:latest # docker save -o qawamis.tar qawamis:latest; docker load qawamis.tar
    container_name: qawamis
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
    volumes:
      - ./config/database.yml:/app/config/database.yml
      - ./config/secrets.yml:/app/config/secrets.yml
      - ./db/database.sqlite3:/app/db/database.sqlite3
      - ./log:/app/log
      - ./tmp:/app/tmp
    restart: unless-stopped
